name: OWASP ZAP Integration - MS105
on: [push] 

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 
          target: 'https://juice-shop.herokuapp.com/'
          rules_file_name: '.zap/rules.tsv'
          fail_action: true 
          cmd_options: '-r zap-report.html' 

 
      - name: Upload ZAP Report
        if: always() 
        uses: actions/upload-artifact@v4
        with:
          name: ZAP-Security-Report
          path: zap-report.html
